---
profiles:
  default:
    network: Mainnet
    private_key: "0xYourPrivateKey"
    public_key: "0xYourPublicKey"
    account: 04191f9658d97a59a0b708b6cfa94b2a1aea2aca272aaa9d1ed421120094cd68
    rest_url: "https://fullnode.mainnet.aptoslabs.com"
